"""init

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 21:08:18.703109

Autogenerated, then hand-checked: every CHECK rule (the plan\'s and the ones added in 6.4) and the
partial "one active tariff" index are here. tests/test_migrations.py guards both.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('routing_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_published_at'), ['published_at'], unique=False)

    op.create_table('processed_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_poysha', sa.Integer(), nullable=False),
    sa.Column('per_km_poysha', sa.Integer(), nullable=False),
    sa.Column('pool_discount_pct', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('base_poysha >= 0 AND per_km_poysha >= 0', name='ck_tariff_nonneg'),
    sa.CheckConstraint('pool_discount_pct BETWEEN 0 AND 100', name='ck_tariff_pct'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.create_index('uq_tariff_one_active', ['active'], unique=True, sqlite_where=sa.text('active = 1'))

    op.create_table('wallets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance_poysha', sa.Integer(), nullable=False),
    sa.CheckConstraint('balance_poysha >= 0', name='ck_wallet_nonneg'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passenger_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_zone', sa.String(length=30), nullable=False),
    sa.Column('dropoff_zone', sa.String(length=30), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('solo_total_poysha', sa.Integer(), nullable=False),
    sa.Column('pooled_total_poysha', sa.Integer(), nullable=False),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('distance_m > 0', name='ck_quote_distance'),
    sa.CheckConstraint('pickup_zone <> dropoff_zone', name='ck_quote_zones'),
    sa.CheckConstraint('pooled_total_poysha >= 0 AND pooled_total_poysha <= solo_total_poysha', name='ck_quote_totals'),
    sa.CheckConstraint('seats BETWEEN 1 AND 6', name='ck_quote_seats'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_passenger_id'), ['passenger_id'], unique=False)

    op.create_table('wallet_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('amount_poysha', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(kind = 'RIDE_DEBIT' AND amount_poysha < 0) OR (kind <> 'RIDE_DEBIT' AND amount_poysha > 0)", name='ck_wtx_sign'),
    sa.CheckConstraint("(kind = 'TOPUP' AND ride_id IS NULL) OR (kind <> 'TOPUP' AND ride_id IS NOT NULL)", name='ck_wtx_ride'),
    sa.CheckConstraint("kind IN ('TOPUP','RIDE_DEBIT','DRIVER_CREDIT')", name='ck_wtx_kind'),
    sa.CheckConstraint('amount_poysha <> 0', name='ck_wtx_nonzero'),
    sa.ForeignKeyConstraint(['user_id'], ['wallets.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'kind', 'user_id', name='uq_wtx_ride_kind_user')
    )
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_wtx_user', ['user_id', 'created_at'], unique=False)

    op.create_table('fares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('pooled', sa.Boolean(), nullable=False),
    sa.Column('base_poysha', sa.Integer(), nullable=False),
    sa.Column('distance_charge_poysha', sa.Integer(), nullable=False),
    sa.Column('pool_discount_poysha', sa.Integer(), nullable=False),
    sa.Column('total_poysha', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.Column('payment_status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("payment_method IN ('CASH','WALLET')", name='ck_fare_method'),
    sa.CheckConstraint("payment_status IN ('PAID','FAILED','REFUNDED')", name='ck_fare_status'),
    sa.CheckConstraint('base_poysha >= 0 AND distance_charge_poysha >= 0 AND pool_discount_poysha >= 0', name='ck_fare_parts_nonneg'),
    sa.CheckConstraint('pooled OR pool_discount_poysha = 0', name='ck_fare_discount_only_pooled'),
    sa.CheckConstraint('seats BETWEEN 1 AND 6', name='ck_fare_seats'),
    sa.CheckConstraint('total_poysha = base_poysha + distance_charge_poysha - pool_discount_poysha', name='ck_fare_arithmetic'),
    sa.CheckConstraint('total_poysha >= 0', name='ck_fare_nonneg'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    with op.batch_alter_table('fares', schema=None) as batch_op:
        batch_op.create_index('ix_fare_driver', ['driver_id', 'created_at'], unique=False)
        batch_op.create_index('ix_fare_passenger', ['passenger_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fares', schema=None) as batch_op:
        batch_op.drop_index('ix_fare_passenger')
        batch_op.drop_index('ix_fare_driver')

    op.drop_table('fares')
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_wtx_user')

    op.drop_table('wallet_transactions')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_passenger_id'))

    op.drop_table('quotes')
    op.drop_table('wallets')
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_index('uq_tariff_one_active', sqlite_where=sa.text('active = 1'))

    op.drop_table('tariffs')
    op.drop_table('processed_events')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_published_at'))

    op.drop_table('outbox')
    # ### end Alembic commands ###
