"""init

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 13:55:17.052153

Autogenerated, then hand-checked (plan 5.9 step 1): both partial unique indexes keep their
sqlite_where, and every CHECK rule is present. tests/test_migrations.py guards both.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_shifts',
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_nickname', sa.String(length=50), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('state_ts', sa.String(length=40), nullable=False),
    sa.CheckConstraint('seat_capacity BETWEEN 1 AND 6', name='ck_shift_capacity'),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('routing_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_published_at'), ['published_at'], unique=False)

    op.create_table('processed_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_nickname', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('occupied_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('pickup_zone', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('FORMING','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_pool_status'),
    sa.CheckConstraint('max_capacity BETWEEN 1 AND 6', name='ck_pool_max'),
    sa.CheckConstraint('occupied_seats >= 0 AND occupied_seats <= max_capacity', name='ck_pool_capacity'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_shifts.driver_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.create_index('ix_pool_matching', ['status', 'pickup_zone'], unique=False)
        batch_op.create_index('uq_pool_one_live_per_driver', ['driver_id'], unique=True, sqlite_where=sa.text("status IN ('FORMING','IN_PROGRESS')"))

    op.create_table('ride_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passenger_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_name', sa.String(length=100), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('pickup_zone', sa.String(length=30), nullable=False),
    sa.Column('dropoff_zone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('solo_distance_m', sa.Integer(), nullable=False),
    sa.Column('estimated_fare_poysha', sa.Integer(), nullable=False),
    sa.Column('estimated_pooled_fare_poysha', sa.Integer(), nullable=False),
    sa.Column('final_fare_poysha', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=10), nullable=True),
    sa.Column('cancel_reason', sa.String(length=200), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("payment_method IN ('CASH','WALLET')", name='ck_ride_payment'),
    sa.CheckConstraint("status = 'REQUESTED' OR status = 'CANCELLED' OR pool_id IS NOT NULL", name='ck_ride_pool_when_matched'),
    sa.CheckConstraint("status IN ('REQUESTED','MATCHED','DRIVER_ARRIVED','STARTED','COMPLETED','CANCELLED')", name='ck_ride_status'),
    sa.CheckConstraint('estimated_fare_poysha >= 0', name='ck_ride_fare'),
    sa.CheckConstraint('pickup_zone <> dropoff_zone', name='ck_ride_zones'),
    sa.CheckConstraint('seats BETWEEN 1 AND 6', name='ck_ride_seats'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ride_requests', schema=None) as batch_op:
        batch_op.create_index('ix_ride_passenger_created', ['passenger_id', 'created_at'], unique=False)
        batch_op.create_index('ix_ride_pool', ['pool_id'], unique=False)
        batch_op.create_index('ix_ride_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('uq_ride_one_active_per_passenger', ['passenger_id'], unique=True, sqlite_where=sa.text("status IN ('REQUESTED','MATCHED','DRIVER_ARRIVED','STARTED')"))

    op.create_table('pool_waypoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('ride_request_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('zone', sa.String(length=30), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('PICKUP','DROPOFF')", name='ck_waypoint_kind'),
    sa.CheckConstraint('seq > 0', name='ck_waypoint_seq'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'seq', name='uq_waypoint_seq')
    )
    op.create_table('ride_offers',
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('OFFERED','ACCEPTED','DECLINED')", name='ck_offer_status'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ride_id', 'driver_id')
    )
    with op.batch_alter_table('ride_offers', schema=None) as batch_op:
        batch_op.create_index('ix_offer_driver', ['driver_id', 'status'], unique=False)

    op.create_table('ride_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("actor_role IN ('PASSENGER','DRIVER','SYSTEM')", name='ck_history_actor'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ride_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_history_ride', ['ride_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_history_ride')

    op.drop_table('ride_status_history')
    with op.batch_alter_table('ride_offers', schema=None) as batch_op:
        batch_op.drop_index('ix_offer_driver')

    op.drop_table('ride_offers')
    op.drop_table('pool_waypoints')
    with op.batch_alter_table('ride_requests', schema=None) as batch_op:
        batch_op.drop_index('uq_ride_one_active_per_passenger', sqlite_where=sa.text("status IN ('REQUESTED','MATCHED','DRIVER_ARRIVED','STARTED')"))
        batch_op.drop_index('ix_ride_status_created')
        batch_op.drop_index('ix_ride_pool')
        batch_op.drop_index('ix_ride_passenger_created')

    op.drop_table('ride_requests')
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_index('uq_pool_one_live_per_driver', sqlite_where=sa.text("status IN ('FORMING','IN_PROGRESS')"))
        batch_op.drop_index('ix_pool_matching')

    op.drop_table('pools')
    op.drop_table('processed_events')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_published_at'))

    op.drop_table('outbox')
    op.drop_table('driver_shifts')
    # ### end Alembic commands ###
