"""init

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 01:19:39.301377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('zone_distances',
    sa.Column('from_zone', sa.String(length=30), nullable=False),
    sa.Column('to_zone', sa.String(length=30), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.CheckConstraint('distance_m > 0', name='ck_distance_positive'),
    sa.CheckConstraint('from_zone <> to_zone', name='ck_distance_distinct'),
    sa.ForeignKeyConstraint(['from_zone'], ['zones.code'], ),
    sa.ForeignKeyConstraint(['to_zone'], ['zones.code'], ),
    sa.PrimaryKeyConstraint('from_zone', 'to_zone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_distances')
    op.drop_table('zones')
    # ### end Alembic commands ###
